name: Aggregate Page Views
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: user-actions
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: page-view-counts
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
