name: Alternative User Actions Generator
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: user-actions
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
